# 这节课是开给完全没有接触过Pytorch的道友的

## 1.关于张量：
1.什么是张量(Tensor) <br>
张量是一种带有**梯度的多维数组(矩阵）** <br>
2.什么是梯度. <br>
可以简单理解为计算过程中**自动求导得到的导数值**

In [3]:
import torch

## 2.创建张量:让我们写代码

In [4]:
## 介绍两种 ,随机初始化和已知初始化.

## 1.torch.randn
a = torch.randn(1,2,3) #随机生成-1~1之间值填充.

## 2.torch.tensor
b = torch.tensor([1,2,3]) # 从数组中创建，创建值和数组一致

In [5]:
a

tensor([[[ 0.0681, -0.6180, -0.2938],
         [ 0.4433, -0.5304, -1.3049]]])

In [6]:
b

tensor([1, 2, 3])

In [7]:
##当然也有一些
## torch.ones,torch.one_like,torch.zeros....都是创建张量，遇到的时候再说

## 3.张量的形状("Shape")

In [8]:
a #三维

tensor([[[ 0.0681, -0.6180, -0.2938],
         [ 0.4433, -0.5304, -1.3049]]])

In [9]:
b #一维

tensor([1, 2, 3])

In [10]:
# 不可能用眼睛看

In [11]:
a.shape # 第一个维度的宽度为1,后依次2,3

torch.Size([1, 2, 3])

In [12]:
b.shape # 长度为3的一维数组

torch.Size([3])

### 3.1改变形状

In [13]:
A = a.reshape(3,2,1)

In [14]:
A,a # 不用记这些值，只要形状对了，就行了hh

(tensor([[[ 0.0681],
          [-0.6180]],
 
         [[-0.2938],
          [ 0.4433]],
 
         [[-0.5304],
          [-1.3049]]]),
 tensor([[[ 0.0681, -0.6180, -0.2938],
          [ 0.4433, -0.5304, -1.3049]]]))

In [15]:
A.shape,a.shape

(torch.Size([3, 2, 1]), torch.Size([1, 2, 3]))

## 4.张量的梯度

梯度(gradient) <br>
在pytorch中叫 requires_grad的一个值可以控制是否保存梯度值 <br>
因为为了节约计算资源，默认创建的张量的时候都是False(不保存) <br>
我们训练的时候会需要这个梯度值。

In [16]:
a.shape

torch.Size([1, 2, 3])

In [17]:
a.requires_grad

False

设置梯度值为True

In [18]:
## 创建后更改
a.requires_grad=True

In [19]:
a.requires_grad

True

In [20]:
a

tensor([[[ 0.0681, -0.6180, -0.2938],
         [ 0.4433, -0.5304, -1.3049]]], requires_grad=True)

In [21]:
## 创建的时候修改
b = torch.randn(1,2,3,requires_grad=True)

In [22]:
b

tensor([[[-1.1968,  1.0503,  0.1116],
         [ 1.0036, -0.5526, -0.8876]]], requires_grad=True)

## 5.补充：随机数种子

In [23]:
c = torch.randn(1,2,3)
c

tensor([[[-0.0853,  1.5822,  0.3895],
         [-1.2896,  0.2566,  1.1798]]])

每次生成的值都不同

In [24]:
torch.manual_seed(42) # 设置随机数种子=42,可以随便设置一个值
c = torch.randn(1,2,3)
c

tensor([[[ 0.3367,  0.1288,  0.2345],
         [ 0.2303, -1.1229, -0.1863]]])

## 6.补充：关于矩阵的乘法

### 点乘 a*b

In [35]:
a

tensor([[[ 0.0681, -0.6180, -0.2938],
         [ 0.4433, -0.5304, -1.3049]]], requires_grad=True)

In [36]:
b

tensor([[[-1.1968,  1.0503,  0.1116],
         [ 1.0036, -0.5526, -0.8876]]], requires_grad=True)

In [39]:
a*b ## 点乘做的事情就是把行列数相同的相乘，但不必自己算，Pytorch帮你算.
a*b[::1]

tensor([[[-0.0815, -0.6491, -0.0328],
         [ 0.4449,  0.2931,  1.1582]]], grad_fn=<MulBackward0>)

In [48]:
a.shape,b.shape

(torch.Size([1, 2, 3]), torch.Size([1, 2, 3]))

In [56]:
# a = a.squeeze(0)
# b = b.squeeze(0)

In [57]:
a.shape,b.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [67]:
print(f"{a}*\n{b}=\n{a*b},\n{a.shape,b.shape}")

tensor([[ 0.0681, -0.6180, -0.2938],
        [ 0.4433, -0.5304, -1.3049]], grad_fn=<SqueezeBackward1>)*
tensor([[-1.1968,  1.0503,  0.1116],
        [ 1.0036, -0.5526, -0.8876]], grad_fn=<SqueezeBackward1>)=
tensor([[-0.0815, -0.6491, -0.0328],
        [ 0.4449,  0.2931,  1.1582]], grad_fn=<MulBackward0>),
(torch.Size([2, 3]), torch.Size([2, 3]))


In [68]:
print(f"{a}*\n{b[0,:]}=\n{a*b[0:,]},\n{a.shape,b[0,:].shape}")

tensor([[ 0.0681, -0.6180, -0.2938],
        [ 0.4433, -0.5304, -1.3049]], grad_fn=<SqueezeBackward1>)*
tensor([-1.1968,  1.0503,  0.1116], grad_fn=<SliceBackward0>)=
tensor([[-0.0815, -0.6491, -0.0328],
        [ 0.4449,  0.2931,  1.1582]], grad_fn=<MulBackward0>),
(torch.Size([2, 3]), torch.Size([3]))


总结: a*b可以成立的情况:<br>
1.(1,2,3)*(1,2,3) 也就是一一对应的情况.<br>
   (2,3)*(2,3) <br>
2.(2,3)*(3)行对列，对应相等,广播点乘，不用记它，几乎不会遇见.

### 叉乘 AXB

In [69]:
A = torch.randn(2,3)
B = torch.randn(3,2)
(A@B).shape  

(2,3)X(3,2) = (2,2)

In [73]:
A = torch.randn(2,2)
B = torch.randn(2,3)
(A@B).shape  

torch.Size([2, 3])

(2,2) X (2,3) =(2,3)

一样不用记计算规则.因为不用自己算

总结: A.shape = (A1,A2) , B.shape = (B1,B2) <br>
     AXB = (A1,A2)X(B1,B2)=(A1,B2)  <br>
     需要A2=B1