# 这节课是开给完全没有接触过Pytorch的道友的

## 1.关于张量：
1.什么是张量(Tensor) <br>
张量是一种带有**梯度的多维数组(矩阵）** <br>
2.什么是梯度. <br>
可以简单理解为计算过程中**自动求导得到的导数值**

## 2.创建张量:让我们写代码

In [7]:
## 介绍两种 ,随机初始化和已知初始化.

## 1.torch.randn
a = torch.randn(1,2,3) #随机生成-1~1之间值填充.

## 2.torch.tensor
b = torch.tensor([1,2,3]) # 从数组中创建，创建值和数组一致

In [8]:
a

tensor([[[-0.6913, -0.2016,  0.4704],
         [ 0.4540, -1.1640,  0.2241]]])

In [9]:
b

tensor([1, 2, 3])

In [ ]:
##当然也有一些
## torch.ones,torch.one_like,torch.zeros....都是创建张量，遇到的时候再说

## 3.张量的形状("Shape")

In [12]:
a #三维

tensor([[[-0.6913, -0.2016,  0.4704],
         [ 0.4540, -1.1640,  0.2241]]])

In [11]:
b #一维

tensor([1, 2, 3])

In [13]:
# 不可能用眼睛看

In [14]:
a.shape # 第一个维度的宽度为1,后依次2,3

torch.Size([1, 2, 3])

In [15]:
b.shape # 长度为3的一维数组

torch.Size([3])

### 3.1改变形状

In [16]:
A = a.reshape(3,2,1)

In [17]:
A,a # 不用记这些值，只要形状对了，就行了hh

(tensor([[[-0.6913],
          [-0.2016]],
 
         [[ 0.4704],
          [ 0.4540]],
 
         [[-1.1640],
          [ 0.2241]]]),
 tensor([[[-0.6913, -0.2016,  0.4704],
          [ 0.4540, -1.1640,  0.2241]]]))

In [18]:
A.shape,a.shape

(torch.Size([3, 2, 1]), torch.Size([1, 2, 3]))

## 4.张量的梯度

梯度(gradient) <br>
在pytorch中叫 requires_grad的一个值可以控制是否保存梯度值 <br>
因为为了节约计算资源，默认创建的张量的时候都是False(不保存) <br>
我们训练的时候会需要这个梯度值。

In [20]:
a.shape

torch.Size([1, 2, 3])

In [21]:
a.requires_grad

False

设置梯度值为True

In [23]:
## 创建后更改
a.requires_grad=True

In [24]:
a.requires_grad

True

In [25]:
a

tensor([[[-0.6913, -0.2016,  0.4704],
         [ 0.4540, -1.1640,  0.2241]]], requires_grad=True)

In [30]:
## 创建的时候修改
b = torch.randn(1,2,3,requires_grad=True)

In [31]:
b

tensor([[[-0.2215,  0.7913,  0.5879],
         [-0.1341,  0.3584, -0.5877]]], requires_grad=True)

## 5.补充：随机数种子

In [37]:
c = torch.randn(1,2,3)
c

tensor([[[-1.4168, -0.0370,  1.2190],
         [ 0.6710, -0.5209,  0.4375]]])

每次生成的值都不同

In [51]:
torch.manual_seed(42) # 设置随机数种子=42,可以随便设置一个值
c = torch.randn(1,2,3)
c

tensor([[[ 0.3367,  0.1288,  0.2345],
         [ 0.2303, -1.1229, -0.1863]]])